services:
  primary-db:
    image: postgres:15
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  secondary-db:
    image: postgres:15
    environment:
      POSTGRES_DB: warehouse_backup
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
