spring:
  application:
    name: warehouse

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: testRouting
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

primary:
  datasource:
    url: jdbc:postgresql://localhost:5433/warehouse
    username: user
    password: pass

secondary:
  datasource:
    url: jdbc:postgresql://localhost:5434/warehouse_backup
    username: user
    password: pass

